export const CLEAN_REDUCER = "CLEAN_REDUCER";

export const LOG_IN = "LOG_IN";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_ERROR = "LOG_IN_ERROR";

export const INVESTIGATIVE_PROJECTS_1_GET = "INVESTIGATIVE_PROJECTS_1_GET";
export const INVESTIGATIVE_PROJECTS_1_GET_SUCCESS = "INVESTIGATIVE_PROJECTS_1_GET_SUCCESS";
export const INVESTIGATIVE_PROJECTS_1_GET_ERROR = "INVESTIGATIVE_PROJECTS_1_GET_ERROR";

export const INVESTIGATIVE_PROJECTS_2_GET = "INVESTIGATIVE_PROJECTS_2_GET";
export const INVESTIGATIVE_PROJECTS_2_GET_SUCCESS = "INVESTIGATIVE_PROJECTS_2_GET_SUCCESS";
export const INVESTIGATIVE_PROJECTS_2_GET_ERROR = "INVESTIGATIVE_PROJECTS_2_GET_ERROR";

export const INVESTIGATIVE_PROJECTS_3_GET = "INVESTIGATIVE_PROJECTS_3_GET";
export const INVESTIGATIVE_PROJECTS_3_GET_SUCCESS = "INVESTIGATIVE_PROJECTS_3_GET_SUCCESS";
export const INVESTIGATIVE_PROJECTS_3_GET_ERROR = "INVESTIGATIVE_PROJECTS_3_GET_ERROR";
 

